# Generated by Django 4.1.3 on 2022-12-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0003_remove_profile_date_profile_user_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ffriend',
            new_name='friends',
        ),
    ]
