# Generated by Django 4.1.3 on 2022-12-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0004_rename_ffriend_profile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('msg_reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_reciever', to='live_chat.profile')),
                ('msg_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender', to='live_chat.profile')),
            ],
        ),
    ]
