# Generated by Django 4.1.3 on 2022-12-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0005_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='passwd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
