# Generated by Django 4.1.3 on 2022-12-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0006_remove_profile_pic_profile_email_profile_passwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
